import { FeaturePlan } from '../models/studio.models.js';

export const plans: FeaturePlan[] = [
  {
    id: 'free',
    name: 'Free',
    description: 'The open-source core. Everything you need to start practicing.',
    features: [
      'Unlimited mock sessions (local)',
      '9 interview tracks, 13 interview modes',
      'Scorecard + rubric feedback',
      '7-day and 14-day study plans',
      'STAR story bank (up to 3 stories)',
      'Markdown export',
      'Ethics guardrails',
      'MIT licensed open-source CLI',
    ],
    limits: {
      sessionsPerDay: 999,
      starStories: 3,
      readinessReports: false,
      pdfExport: false,
      resumeJdQuestions: false,
      premiumPacks: false,
      teamDashboard: false,
    },
  },
  {
    id: 'pro',
    name: 'Pro',
    description: 'Full preparation toolkit for active job seekers.',
    priceMonthly: 9,
    priceYearly: 79,
    features: [
      'Everything in Free',
      'Full readiness reports (weakness map, hire signal, 30-day plan)',
      'Unlimited STAR story bank',
      'Progress dashboard',
      'Advanced weakness map',
      'PDF-ready export',
      'Priority mode suggestions',
    ],
    limits: {
      sessionsPerDay: 999,
      starStories: 999,
      readinessReports: true,
      pdfExport: true,
      resumeJdQuestions: false,
      premiumPacks: false,
      teamDashboard: false,
    },
    recommended: true,
  },
  {
    id: 'job-hunt',
    name: 'Job Hunt Mode',
    description: 'For developers actively interviewing who want maximum context.',
    priceMonthly: 19,
    priceYearly: 149,
    features: [
      'Everything in Pro',
      'Resume/JD-aware interview questions',
      'Company-specific prep packs',
      '30-day job hunt study plan',
      'Premium question packs included',
      'Advanced role-fit analysis',
    ],
    limits: {
      sessionsPerDay: 999,
      starStories: 999,
      readinessReports: true,
      pdfExport: true,
      resumeJdQuestions: true,
      premiumPacks: true,
      teamDashboard: false,
    },
  },
  {
    id: 'lifetime',
    name: 'Lifetime Early Bird',
    description: 'Support the project and get Pro features forever.',
    priceOneTime: 49,
    features: [
      'Everything in Pro',
      'Lifetime access',
      'Early-access features',
      'Supporter recognition',
    ],
    limits: {
      sessionsPerDay: 999,
      starStories: 999,
      readinessReports: true,
      pdfExport: true,
      resumeJdQuestions: false,
      premiumPacks: false,
      teamDashboard: false,
    },
  },
  {
    id: 'team',
    name: 'Team / Bootcamp',
    description: 'For bootcamps, career coaches, and hiring teams.',
    priceMonthly: 5,
    features: [
      'Everything in Pro',
      'Team dashboard (coming soon)',
      'Cohort progress tracking',
      'Custom track upload',
      'Bulk session management',
    ],
    limits: {
      sessionsPerDay: 999,
      starStories: 999,
      readinessReports: true,
      pdfExport: true,
      resumeJdQuestions: true,
      premiumPacks: true,
      teamDashboard: true,
    },
  },
];
