import { Router } from 'express';
import type { InterviewSession } from '../models/studio.models.js';
import { sessionStore } from '../services/session-store.service.js';
import { getReadinessReport } from '../services/readiness-report.service.js';

const router = Router();

router.get('/sessions/:id/export/markdown', async (req, res) => {
  try {
    const session = await sessionStore.get(req.params['id']);
    if (!session) {
      res.status(404).json({ error: 'Session not found.' });
      return;
    }
    const md = buildMarkdown(session);
    res.setHeader('Content-Type', 'text/markdown; charset=utf-8');
    res.setHeader('Content-Disposition', `attachment; filename="session-${session.id}.md"`);
    res.send(md);
  } catch (err) {
    const message = err instanceof Error ? err.message : 'Unknown error';
    res.status(500).json({ error: message });
  }
});

router.get('/sessions/:id/export/html', async (req, res) => {
  try {
    const session = await sessionStore.get(req.params['id']);
    if (!session) {
      res.status(404).json({ error: 'Session not found.' });
      return;
    }
    const html = buildHtml(session);
    res.setHeader('Content-Type', 'text/html; charset=utf-8');
    res.setHeader('Content-Disposition', `attachment; filename="session-${session.id}.html"`);
    res.send(html);
  } catch (err) {
    const message = err instanceof Error ? err.message : 'Unknown error';
    res.status(500).json({ error: message });
  }
});

function buildMarkdown(session: InterviewSession): string {
  const lines: string[] = [];

  lines.push(`# Interview Practice Session`);
  lines.push('');
  lines.push(`**Track:** ${session.track}`);
  lines.push(`**Mode:** ${session.mode}`);
  lines.push(`**Provider:** ${session.provider}`);
  lines.push(`**Status:** ${session.status}`);
  lines.push(`**Date:** ${session.createdAt}`);
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('## Conversation');
  lines.push('');

  for (const msg of session.messages) {
    const label = msg.role.charAt(0).toUpperCase() + msg.role.slice(1);
    lines.push(`### ${label}`);
    lines.push('');
    lines.push(msg.content);
    lines.push('');
  }

  if (session.scorecard) {
    lines.push('---');
    lines.push('');
    lines.push('## Scorecard');
    lines.push('');
    lines.push(`**Overall Score:** ${session.scorecard.overallScore} / ${session.scorecard.maxScore}`);
    lines.push(`**Hire Signal:** ${session.scorecard.hireSignal}`);
    lines.push('');

    for (const dim of session.scorecard.dimensions) {
      lines.push(`- **${dim.name}** (${dim.score}/5): ${dim.feedback}`);
    }
    lines.push('');
  }

  if (session.studyPlan) {
    lines.push('---');
    lines.push('');
    lines.push('## Study Plan');
    lines.push('');
    lines.push('### 7-Day Plan');
    lines.push('');
    for (const item of session.studyPlan.sevenDayPlan) {
      lines.push(`- ${item}`);
    }
    lines.push('');
    lines.push('### 14-Day Plan');
    lines.push('');
    for (const item of session.studyPlan.fourteenDayPlan) {
      lines.push(`- ${item}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push('*Generated by InterviewOps Studio — Practice-only mode*');

  return lines.join('\n');
}

function buildHtml(session: InterviewSession): string {
  const escape = (s: string) =>
    s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

  const parts: string[] = [];

  parts.push(`<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Interview Practice Session - ${escape(session.id)}</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 800px; margin: 0 auto; padding: 40px 20px; color: #1a1a2e; background: #fafafa; line-height: 1.6; }
  h1 { font-size: 24px; margin-bottom: 16px; color: #0f0f23; }
  h2 { font-size: 18px; margin: 24px 0 12px; color: #1a1a2e; border-bottom: 2px solid #e0e0e0; padding-bottom: 6px; }
  h3 { font-size: 14px; margin: 16px 0 8px; text-transform: uppercase; letter-spacing: 0.5px; }
  .meta { background: #f0f0f5; padding: 16px; border-radius: 8px; margin-bottom: 24px; font-size: 14px; }
  .meta p { margin: 4px 0; }
  .message { padding: 12px 16px; margin: 8px 0; border-radius: 8px; font-size: 14px; }
  .message-system { background: #e8eaf6; color: #3949ab; }
  .message-interviewer { background: #e3f2fd; color: #1565c0; }
  .message-candidate { background: #e8f5e9; color: #2e7d32; }
  .message-coach { background: #fff3e0; color: #e65100; }
  .message-label { font-weight: 600; font-size: 12px; text-transform: uppercase; letter-spacing: 0.5px; margin-bottom: 4px; }
  .scorecard { background: #f5f5f5; padding: 20px; border-radius: 8px; margin: 16px 0; }
  .score-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 16px; }
  .score-number { font-size: 36px; font-weight: 700; color: #1a1a2e; }
  .score-max { font-size: 18px; color: #666; }
  .hire-signal { padding: 6px 16px; border-radius: 20px; font-weight: 600; font-size: 13px; }
  .signal-positive { background: #c8e6c9; color: #2e7d32; }
  .signal-neutral { background: #fff9c4; color: #f57f17; }
  .signal-negative { background: #ffcdd2; color: #c62828; }
  .dimension { margin: 12px 0; }
  .dim-name { font-weight: 600; }
  .dim-score { color: #666; }
  .dim-bar { height: 6px; background: #e0e0e0; border-radius: 3px; margin: 4px 0; }
  .dim-fill { height: 100%; background: #7c3aed; border-radius: 3px; }
  .dim-feedback { font-size: 13px; color: #555; }
  .plan-item { padding: 4px 0; font-size: 14px; }
  .footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #e0e0e0; font-size: 12px; color: #999; text-align: center; }
  @media print { body { padding: 20px; } }
</style>
</head>
<body>`);

  parts.push(`<h1>Interview Practice Session</h1>`);
  parts.push(`<div class="meta">
  <p><strong>Track:</strong> ${escape(session.track)}</p>
  <p><strong>Mode:</strong> ${escape(session.mode)}</p>
  <p><strong>Provider:</strong> ${escape(session.provider)}</p>
  <p><strong>Status:</strong> ${escape(session.status)}</p>
  <p><strong>Date:</strong> ${escape(session.createdAt)}</p>
</div>`);

  parts.push(`<h2>Conversation</h2>`);
  for (const msg of session.messages) {
    const label = msg.role.charAt(0).toUpperCase() + msg.role.slice(1);
    parts.push(`<div class="message message-${escape(msg.role)}">
  <div class="message-label">${escape(label)}</div>
  <div>${escape(msg.content).replace(/\n/g, '<br>')}</div>
</div>`);
  }

  if (session.scorecard) {
    const signalClass = session.scorecard.hireSignal.includes('No')
      ? 'signal-negative'
      : session.scorecard.hireSignal === 'Lean Hire'
        ? 'signal-neutral'
        : 'signal-positive';

    parts.push(`<h2>Scorecard</h2>
<div class="scorecard">
  <div class="score-header">
    <div><span class="score-number">${session.scorecard.overallScore}</span><span class="score-max"> / ${session.scorecard.maxScore}</span></div>
    <span class="hire-signal ${signalClass}">${escape(session.scorecard.hireSignal)}</span>
  </div>`);

    for (const dim of session.scorecard.dimensions) {
      const pct = (dim.score / 5) * 100;
      parts.push(`  <div class="dimension">
    <div><span class="dim-name">${escape(dim.name)}</span> <span class="dim-score">${dim.score}/5</span></div>
    <div class="dim-bar"><div class="dim-fill" style="width: ${pct}%"></div></div>
    <div class="dim-feedback">${escape(dim.feedback)}</div>
  </div>`);
    }
    parts.push(`</div>`);
  }

  if (session.studyPlan) {
    parts.push(`<h2>Study Plan</h2>`);
    parts.push(`<h3>7-Day Plan</h3>`);
    for (const item of session.studyPlan.sevenDayPlan) {
      parts.push(`<div class="plan-item">${escape(item)}</div>`);
    }
    parts.push(`<h3>14-Day Plan</h3>`);
    for (const item of session.studyPlan.fourteenDayPlan) {
      parts.push(`<div class="plan-item">${escape(item)}</div>`);
    }
  }

  parts.push(`<div class="footer">Generated by InterviewOps Studio &mdash; Practice-only mode</div>`);
  parts.push(`</body></html>`);

  return parts.join('\n');
}

export default router;
