import { Router } from 'express';

const router = Router();

const providers = [
  {
    id: 'mock',
    name: 'Mock (Offline)',
    icon: '🤖',
    badge: 'Free',
    description: 'Built-in mock interviewer. Works offline, no API key needed.',
    requiresKey: false,
    models: [
      { id: 'mock-default', name: 'Mock Interviewer v1', recommended: true },
    ],
    setupSteps: [],
  },
  {
    id: 'openai',
    name: 'OpenAI',
    icon: '⚡',
    badge: 'GPT-4o',
    description: 'Powered by OpenAI GPT-4o. Best reasoning and instruction-following.',
    requiresKey: true,
    keyEnvVar: 'OPENAI_API_KEY',
    docsUrl: 'https://platform.openai.com/api-keys',
    models: [
      { id: 'gpt-4o', name: 'GPT-4o', recommended: true },
      { id: 'gpt-4o-mini', name: 'GPT-4o mini — faster & cheaper' },
      { id: 'gpt-4-turbo', name: 'GPT-4 Turbo' },
      { id: 'o3-mini', name: 'o3-mini — advanced reasoning' },
      { id: 'o1-mini', name: 'o1-mini — reasoning' },
    ],
    setupSteps: [
      'Go to platform.openai.com and sign in (or create a free account)',
      'In the left sidebar, click "API keys"',
      'Click "Create new secret key" and give it a name',
      'Copy the key — it starts with "sk-..."',
      'In the studio-api directory, create a .env file (or open the existing one)',
      'Add the line: OPENAI_API_KEY=sk-your-key-here',
      'Restart the API server with: npm run dev',
    ],
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    icon: '🧠',
    badge: 'Claude',
    description: 'Powered by Claude. Exceptional nuance, long context, and safety.',
    requiresKey: true,
    keyEnvVar: 'ANTHROPIC_API_KEY',
    docsUrl: 'https://console.anthropic.com/settings/keys',
    models: [
      { id: 'claude-opus-4-6', name: 'Claude Opus 4.6 — most capable', recommended: true },
      { id: 'claude-sonnet-4-6', name: 'Claude Sonnet 4.6 — balanced' },
      { id: 'claude-haiku-4-5-20251001', name: 'Claude Haiku 4.5 — fastest' },
    ],
    setupSteps: [
      'Go to console.anthropic.com and sign in (or create an account)',
      'Click "API Keys" in the left navigation',
      'Click "Create Key" and give it a name',
      'Copy the key — it starts with "sk-ant-..."',
      'In the studio-api directory, open or create a .env file',
      'Add the line: ANTHROPIC_API_KEY=sk-ant-your-key-here',
      'Restart the API server with: npm run dev',
    ],
  },
  {
    id: 'gemini',
    name: 'Gemini',
    icon: '✨',
    badge: 'Google',
    description: 'Powered by Google Gemini. Strong at multi-turn reasoning and code.',
    requiresKey: true,
    keyEnvVar: 'GEMINI_API_KEY',
    docsUrl: 'https://aistudio.google.com/app/apikey',
    models: [
      { id: 'gemini-2.0-flash', name: 'Gemini 2.0 Flash', recommended: true },
      { id: 'gemini-2.0-flash-lite', name: 'Gemini 2.0 Flash Lite — faster' },
      { id: 'gemini-1.5-pro', name: 'Gemini 1.5 Pro — long context' },
      { id: 'gemini-1.5-flash', name: 'Gemini 1.5 Flash' },
    ],
    setupSteps: [
      'Go to aistudio.google.com and sign in with your Google account',
      'Click "Get API key" in the top-left corner',
      'Click "Create API key in new project" (or select an existing project)',
      'Copy the generated API key',
      'In the studio-api directory, open or create a .env file',
      'Add the line: GEMINI_API_KEY=your-key-here',
      'Restart the API server with: npm run dev',
    ],
  },
  {
    id: 'groq',
    name: 'Groq',
    icon: '🚀',
    badge: 'Fast',
    description: 'Llama 3 on Groq hardware. Extremely fast inference, generous free tier.',
    requiresKey: true,
    keyEnvVar: 'GROQ_API_KEY',
    docsUrl: 'https://console.groq.com/keys',
    models: [
      { id: 'llama-3.3-70b-versatile', name: 'Llama 3.3 70B Versatile', recommended: true },
      { id: 'llama-3.1-8b-instant', name: 'Llama 3.1 8B Instant — ultra fast' },
      { id: 'mixtral-8x7b-32768', name: 'Mixtral 8x7B' },
      { id: 'gemma2-9b-it', name: 'Gemma 2 9B' },
    ],
    setupSteps: [
      'Go to console.groq.com and sign in (or create a free account)',
      'In the sidebar, click "API Keys"',
      'Click "Create API Key" and give it a name',
      'Copy the key — it starts with "gsk_..."',
      'In the studio-api directory, open or create a .env file',
      'Add the line: GROQ_API_KEY=gsk_your-key-here',
      'Restart the API server with: npm run dev',
      'Note: Groq has a generous free tier — great for practice!',
    ],
  },
  {
    id: 'together',
    name: 'Together AI',
    icon: '🤝',
    badge: 'Open Models',
    description: 'Run 100+ open-source models via Together AI. Pay-as-you-go, cheap.',
    requiresKey: true,
    keyEnvVar: 'TOGETHER_API_KEY',
    docsUrl: 'https://api.together.xyz/settings/api-keys',
    models: [
      { id: 'meta-llama/Llama-3.3-70B-Instruct-Turbo', name: 'Llama 3.3 70B Turbo', recommended: true },
      { id: 'meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo', name: 'Llama 3.1 8B Turbo — fast' },
      { id: 'mistralai/Mixtral-8x22B-Instruct-v0.1', name: 'Mixtral 8x22B' },
      { id: 'Qwen/Qwen2.5-72B-Instruct-Turbo', name: 'Qwen 2.5 72B' },
      { id: 'deepseek-ai/DeepSeek-V3', name: 'DeepSeek V3' },
    ],
    setupSteps: [
      'Go to api.together.xyz and sign in (or create an account)',
      'Click your profile in the top right → "API Keys"',
      'Click "Create" to generate a new key',
      'Copy the key',
      'In the studio-api directory, open or create a .env file',
      'Add the line: TOGETHER_API_KEY=your-key-here',
      'Restart the API server with: npm run dev',
      'Tip: New accounts get $5 in free credits to get started.',
    ],
  },
  {
    id: 'mistral',
    name: 'Mistral',
    icon: '🌊',
    badge: 'EU AI',
    description: 'European open-weight models. Strong reasoning with low latency.',
    requiresKey: true,
    keyEnvVar: 'MISTRAL_API_KEY',
    docsUrl: 'https://console.mistral.ai/api-keys',
    models: [
      { id: 'mistral-large-latest', name: 'Mistral Large — most capable', recommended: true },
      { id: 'mistral-small-latest', name: 'Mistral Small — fast & cheap' },
      { id: 'open-mixtral-8x22b', name: 'Mixtral 8x22B' },
      { id: 'codestral-latest', name: 'Codestral — best for coding tracks' },
    ],
    setupSteps: [
      'Go to console.mistral.ai and sign in (or create an account)',
      'In the left sidebar, click "API Keys"',
      'Click "Create new key" and give it a name',
      'Copy the key',
      'In the studio-api directory, open or create a .env file',
      'Add the line: MISTRAL_API_KEY=your-key-here',
      'Restart the API server with: npm run dev',
    ],
  },
  {
    id: 'ollama',
    name: 'Ollama',
    icon: '🦙',
    badge: 'Local',
    description: 'Run models 100% locally on your machine. Private, free, no internet.',
    requiresKey: false,
    keyEnvVar: undefined,
    docsUrl: 'https://ollama.com',
    models: [
      { id: 'llama3.2', name: 'Llama 3.2 3B — fast & small', recommended: true },
      { id: 'llama3.3', name: 'Llama 3.3 70B — most capable' },
      { id: 'mistral', name: 'Mistral 7B' },
      { id: 'qwen2.5', name: 'Qwen 2.5 7B' },
      { id: 'phi4', name: 'Phi-4 — Microsoft' },
      { id: 'deepseek-r1:8b', name: 'DeepSeek R1 8B' },
    ],
    setupSteps: [
      'Download Ollama from ollama.com/download for your OS (Mac, Windows, Linux)',
      'Install it and open a terminal',
      'Pull the model you want, e.g.: ollama pull llama3.2',
      'Ollama will start a local server at http://localhost:11434 automatically',
      'No API key needed — InterviewOps connects directly to the local server',
      'Tip: Larger models (70B) need 32GB+ RAM. Smaller ones (3B–8B) run fine on most laptops.',
    ],
  },
  {
    id: 'cohere',
    name: 'Cohere',
    icon: '🔷',
    badge: 'Enterprise',
    description: 'Command R+ by Cohere. Optimised for RAG and enterprise use-cases.',
    requiresKey: true,
    keyEnvVar: 'COHERE_API_KEY',
    docsUrl: 'https://dashboard.cohere.com/api-keys',
    models: [
      { id: 'command-r-plus', name: 'Command R+ — most capable', recommended: true },
      { id: 'command-r', name: 'Command R — balanced' },
      { id: 'command-light', name: 'Command Light — fastest' },
    ],
    setupSteps: [
      'Go to dashboard.cohere.com and sign in (or create an account)',
      'In the left sidebar, click "API Keys"',
      'Copy your trial key, or click "New Trial Key" to generate one',
      'In the studio-api directory, open or create a .env file',
      'Add the line: COHERE_API_KEY=your-key-here',
      'Restart the API server with: npm run dev',
      'Note: Trial keys are free and rate-limited but perfect for practice.',
    ],
  },
];

router.get('/providers', (_req, res) => {
  res.json(providers);
});

export default router;
